import {
  siApachekafka,
  siClaude,
  siCloudflare,
  siCypress,
  siD3,
  siDart,
  siDocker,
  siExpress,
  siFigma,
  siFirebase,
  siGit,
  siGraphql,
  siJavascript,
  siModelcontextprotocol,
  siMongodb,
  siNestjs,
  siNetlify,
  siNextdotjs,
  siNodedotjs,
  siNuxt,
  siPinia,
  siPostgresql,
  siPostman,
  siPrisma,
  siPython,
  siRabbitmq,
  siRaspberrypi,
  siReact,
  siRedis,
  siRedux,
  siSass,
  siSocketdotio,
  siStorybook,
  siSupabase,
  siTailwindcss,
  siTanstack,
  siTypeorm,
  siTypescript,
  siVercel,
  siVite,
  siVitest,
  siVuedotjs,
} from 'simple-icons'

/** Four-point star matching the marquee separators — used for tech without a brand icon (AWS/Zustand are trademark-removed from simple-icons). */
const FALLBACK_PATH =
  'M12 2l2.4 7.6L22 12l-7.6 2.4L12 22l-2.4-7.6L2 12l7.6-2.4z'

export class TechIcons {
  static readonly #paths: Record<string, string> = {
    TypeScript: siTypescript.path,
    JavaScript: siJavascript.path,
    Python: siPython.path,
    Dart: siDart.path,
    React: siReact.path,
    'Next.js': siNextdotjs.path,
    'Vue.js': siVuedotjs.path,
    Nuxt: siNuxt.path,
    TanStack: siTanstack.path,
    Redux: siRedux.path,
    Pinia: siPinia.path,
    'Tailwind CSS': siTailwindcss.path,
    Sass: siSass.path,
    Storybook: siStorybook.path,
    Vite: siVite.path,
    'Node.js': siNodedotjs.path,
    Express: siExpress.path,
    NestJS: siNestjs.path,
    GraphQL: siGraphql.path,
    PostgreSQL: siPostgresql.path,
    MongoDB: siMongodb.path,
    Redis: siRedis.path,
    Prisma: siPrisma.path,
    TypeORM: siTypeorm.path,
    Supabase: siSupabase.path,
    Firebase: siFirebase.path,
    Docker: siDocker.path,
    RabbitMQ: siRabbitmq.path,
    Git: siGit.path,
    Cloudflare: siCloudflare.path,
    Vercel: siVercel.path,
    Netlify: siNetlify.path,
    Cypress: siCypress.path,
    Vitest: siVitest.path,
    Postman: siPostman.path,
    Figma: siFigma.path,
    Claude: siClaude.path,
    MCP: siModelcontextprotocol.path,
    Kafka: siApachekafka.path,
    'D3.js': siD3.path,
    'Socket.IO': siSocketdotio.path,
    'React Native': siReact.path,
    'Raspberry Pi': siRaspberrypi.path,
  }

  static path(label: string): string {
    return TechIcons.#paths[label] ?? FALLBACK_PATH
  }
}
